### ISSUE TITLE
How to use your project with Nodejs ?

### ISSUE THREAD

**Issue by HADDADENICAR** [rowanwins/supercluster-server#1]
You don't have any **get** method in *index.js* ? when i run:

> node index.js 
i get a message in the console that the server is listening in port 7777 : 

      Server listening on port 7777
      Data loaded for randomPoints
      creating index for randomPoints
      endpoint created at http://localhost:7777/randomPoints

however when i point my browser to http://localhost:7777 or http://localhost:7777/randomPoints i get an error telling that there is no get method : 

> Cannot  GET / 
or 
> Cannot GET /randompoints/

So how you launch this project in your machine ?

**Comment by rowanwins** [comment]
Hi @HADDADENICAR 

There is an example of how to use the lib [in here](https://github.com/rowanwins/supercluster-server/blob/master/test/index.js#L44-L47),you basically need to pass through the bounds of your area of interest

**Comment by HADDADENICAR** [comment]
Hi @rowanwins  I just learned **NodeJS** and what i know from my learning that  we can  run   our project from an **index.js** File, Like this:

> $node index.js 

,and then  pointing the browser to the port where the server is listening  (here *localhost:7777*).


In your response you pinpoint the test folder where i found an ***index.html*** file, i launched it and supercluster is working in Australia map.
But this is weird !!! ,  when i learned NodeJS the serving was always via a get method ?

**Comment by rowanwins** [comment]
I'm using [expressjs](http://expressjs.com/), which is a nodejs library, to expose a web service which can then be consumed in other applications.

NodeJS allows you to do many things and so it depends a bit on what you are trying to achieve. In the case of this library I was envisaging a central data store which published web services to be consumed by an application, like a web site.

**Comment by spkostas** [comment]
I dont quite get the idea of passing the bounds of exact area.So each time i have to specify the bounds in order to see the clustering?
